### PR TITLE
Update Twilio Video iOS to 5.0.0

### PR DESCRIPTION
**Pull request by 4brunu**
This one updated the Twilio Video iOS binding to the latest 5.0.0 version
https://github.com/twilio/twilio-video-ios/releases/tag/5.0.0
https://www.twilio.com/docs/video/changelog-twilio-video-ios-latest#500-february-14-2022

Here are the diff's of ApiDefinitions and StructsAndEnums between version 4.6.3 and 5.0.0.
[StructsAndEnums-4.6.3-5.0.0.patch.txt](https://github.com/xamarin-bindings-for-twilio/TwilioVideoXamarinIOS/files/8062164/StructsAndEnums-4.6.3-5.0.0.patch.txt)
[ApiDefinitions-4.6.3-5.0.0.patch.txt](https://github.com/xamarin-bindings-for-twilio/TwilioVideoXamarinIOS/files/8062166/ApiDefinitions-4.6.3-5.0.0.patch.txt)

Here are the ApiDefinitions and StructsAndEnums of version 4.6.3.
[ApiDefinitions-4.6.3.cs.txt](https://github.com/xamarin-bindings-for-twilio/TwilioVideoXamarinIOS/files/8062179/ApiDefinitions-4.6.3.cs.txt)
[StructsAndEnums-4.6.3.cs.txt](https://github.com/xamarin-bindings-for-twilio/TwilioVideoXamarinIOS/files/8062180/StructsAndEnums-4.6.3.cs.txt)

Here are the ApiDefinitions and StructsAndEnums of version 5.0.0.
[ApiDefinitions-5.0.0.cs.txt](https://github.com/xamarin-bindings-for-twilio/TwilioVideoXamarinIOS/files/8062183/ApiDefinitions-5.0.0.cs.txt)
[StructsAndEnums-5.0.0.cs.txt](https://github.com/xamarin-bindings-for-twilio/TwilioVideoXamarinIOS/files/8062184/StructsAndEnums-5.0.0.cs.txt)

### CODE REVIEW

**Review by krnvd — APPROVED** [review]
Looking good.

**Comment by 4brunu** [comment]
@krnvd thanks for reviewing this PR. Do you want to publish this update to nuget, or do you want me to do it?

**Comment by krnvd** [comment]
@4brunu you can publish it. Let me know if you need any help with it.

**Comment by 4brunu** [comment]
Done 👍

**Pull request merged**
